#!/usr/bin/env zsh
#
# fbas - Bastion Host Connection with fzf
#
# Description:
#   ~/.bastion/config から Bastion ホストを fzf で選択し、接続する
#   選択時に設定内容をプレビュー表示
#
# Usage:
#   fbas
#
fbas() {
    local bastion_host=$(cat ~/.bastion/config |
        grep -i ^host |
        awk '{print $2}' |
        fzf --prompt "Select Bastion Host. > " \
          --height 50% --layout=reverse --border --preview-window 'right:50%' \
        --preview "grep {} -A2 ~/.bastion/config")

    if [ "$bastion_host" = "" ]; then
        # ex) Ctrl-C.
        return 1
    fi
    connect_bastion ${bastion_host}
}

