#!/usr/bin/env zsh
#
# fh - Command History Search with fzf
#
# Description:
#   コマンド履歴を fzf で検索・選択して実行
#   選択したコマンドは自動的にコマンドラインに挿入される
#
# Usage:
#   fh
#
fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed -E 's/ *[0-9]*\*? *//' | sed -E 's/\\/\\\\/g')
}

