#!/usr/bin/env zsh
#
# funbrew - Homebrew Package Uninstall with fzf
#
# Description:
#   インストール済みの Homebrew パッケージを fzf で選択してアンインストール
#   複数パッケージの同時選択・アンインストールが可能（Tab で複数選択）
#   brew leaves でトップレベルパッケージのみを表示
#
# Usage:
#   funbrew
#
funbrew() {
  local uninst=$(brew leaves | fzf -m)

  if [[ $uninst ]]; then
    for prog in $(echo $uninst);
    do; brew uninstall $prog; done;
  fi
}

